### ISSUE TITLE
Zoom value of timeline in saved views

### ISSUE THREAD

**Issue by JStratil** [oaubert/advene#11]
When saving a view of the timeline the zoom value of the timeline is not correctly saved. (Changing e.g. from 77% to 59% when reopening the saved view or 100% to 77%.)

**Comment by AdaTsche** [comment]
If you limit a view to a certain part of the timeline, this limitation cannot be saved with the save-timeline-feature. The zoom values in percent are then not meaningfull at all, since their point of reference is different.
