### ISSUE TITLE
Timeline problems with longer videos

### ISSUE THREAD

**Issue by AdaTsche** [oaubert/advene#14]
A further observation concerning the timeline problems when dealing with more than 1k annotations in a file: 
We annotated the first scene of a film with 1200 annotations and we used a video of only this first scene.  Even with this amount of annotations advene ran relatively smoothly. 
When we then switched the video for a video file of the whole film advene had massive lags (also after waiting for several minutes to create all neccessary screenshots). 
So not only the number of annotations but also the length of the video file seems to be important for the capacity problem.

**Comment by oaubert** [comment]
After investigation and test in place, the problem does not lie in the video player itself, but rather on the timeline handling not very well movie duration changes (when switching from a short video to a longer one). If the timeline is closed and reopened *after switching the video*, performance is normal.
