### ISSUE TITLE
Timecode Synchronization of video player (evaluation of test video)

### ISSUE THREAD

**Issue by JStratil** [oaubert/advene#15]
After testing the test video in our advene setup we found some minor deviation of the timecode of the timeline/player and the burned-in timecode of the video. When playing and then pausing the video the timecode is either the same (see screenshot "Played&Paused2) 
![played paused2](https://cloud.githubusercontent.com/assets/25327867/23658052/4e730d90-0341-11e7-973a-da25a9137d02.png)
or deviates by 40ms (25fps) ("Played&Paused1). 
![played paused1](https://cloud.githubusercontent.com/assets/25327867/23658069/637592ee-0341-11e7-9752-8e72af60d1b3.png)
However after clicking on the annotation with the deviation in the table view the timecode is synchronized. (see screenshot) 
![played paused1_after clicking on the annotation in table view](https://cloud.githubusercontent.com/assets/25327867/23658082/72e21a90-0341-11e7-821d-e321f65bb2dc.png)
When clicking in the timeline the player timecode und burned-in-video timecode deviate by different amounts (approx. 5ms-30ms) (see screenshot "Clicking in the timeline_1) 
![click in timeline_1](https://cloud.githubusercontent.com/assets/25327867/23658097/808cab60-0341-11e7-90da-a1b6498ec8a1.png)

This deviation stays the same when maneuvering frame forward or backward. (see screenshot: ![click in timeline_1](https://cloud.githubusercontent.com/assets/25327867/23657599/31a29692-033f-11e7-9f77-00baf7f20822.png)
![click in timeline_1_1frame forward]

**Comment by oaubert** [comment]
Not having the exact same timecode, within 40ms, is normal, since the frame at 1:27.800 is valid for times between 1:27.800 and 1:27.840.

**Comment by oaubert** [comment]
I have updated the test video at http://olivieraubert.net/advene/timecode_test_video.mp4 by enlarging the font so that the timecode is readable on the thumbnails. It will help identify precision issues in thumbnailing.
