### ISSUE TITLE
Splitting an Annotation in Shot Validation View

### ISSUE THREAD

**Issue by AdaTsche** [oaubert/advene#34]
When trying to slplit an annotation in shot vlaidation view by clicking on a frame while holding ctrl the log shows the following error: 
17:32:24 - Shot validation view: Cannot split annotation #37: out of bounds.
When I then enter timline view and select "Split annotation at player position" its no problem and the division works fine.

**Comment by oaubert** [comment]
It is because you are trying to split the annotation *before* the current cut. Ctrl-click will try to create an annotation starting at the current indicated timecode, and the new clicked timecode. So you have to insert the new bound after the current timecode.
