### ISSUE TITLE
Sound Enveloppe doesn't create Annotations

### ISSUE THREAD

**Issue by AdaTsche** [oaubert/advene#35]
When processing a .mp4 video with mpeg AAC audio codec the Sound Enveloppe filter does only create an annotation type but no annotation. Changes in number of samples and selecting only one of the stereo channels doesn't solve the problem.
The advene video player has no problem with the audio codec.

**Comment by oaubert** [comment]
Could you try again to see if it fixed in current git version?

**Comment by AdaTsche** [comment]
Solved ... only a problem with absolute silence remains where it is depicted as full volume
