### ISSUE TITLE
missing 'debian' folder

### ISSUE THREAD

**Issue by pchampin** [oaubert/advene#36]
``setup.py`` refers to a file ``debian/advene.desktop``

https://github.com/oaubert/advene/blob/3fedf019340ec71c290afdc89eef54f3a929e4a6/setup.py#L157

but this file does not exist in the repository. Forgot a ``git add``? ;-)

**Comment by oaubert** [comment]
Rather the remains of a "git rm" when I split the debian packaging from the main source tree.
