### ISSUE TITLE
Tagging of annotations: All tags uncolored when deleting a tag

### ISSUE THREAD

**Issue by JStratil** [oaubert/advene#45]
When deleting the tag of one annotation, all other annotations that have been tagged are uncolored, though they are still tagged. (Creating a new tag with the same name but a different color causes that all annotations prior tagged are colored in the new color, even the one the tag was completely deleted from.)

**Comment by oaubert** [comment]
Fixed in 80f21afae72f841612e10bbac2ef43cf4f517fce
