### ISSUE TITLE
Input of multiple values in autocomplete and Quick Fill

### ISSUE THREAD

**Issue by JStratil** [oaubert/advene#50]
A useful feature would be the possibility to annotate multiple values with autocomplete and Quick Fill (i.e. in annotation types where multiple values are allowed). 
In Autocomplete: After a seperator (space?) autocomplete-Suggestions start again/ work again. 
In Quick Fill: First ideas: Either by a timeframe (All numbers entered in a specific timeframe) or by another seperator: So one would enter: Number ShortcutForSeperator Number
A Follow-Up-Idea could be also relevant for the ontology: syntax elements like [TO] could become values in itself and could then be entered via autocomplete or Quick Fill.

**Comment by oaubert** [comment]
There were multiple issues here.
- autocomplete in Table and Timeline provides completion on each word
- for Quick fill, shortcut 1-9 now *toggle* the corresponding keyword, so they can be used to enter multiple values. See [../wiki/AdveneShortcuts#annotation-widget](AdveneShortcuts) and [../wiki/Timeline_View#using-predefined-keywords-to-quickly-input-content](Timeline View) wiki documentation for more details.
