### ISSUE TITLE
Package cannot be saved

### ISSUE THREAD

**Issue by AdaTsche** [oaubert/advene#6]
During annotating saving the progress isn't possible anymore. When I click "Save package" or "Save package as" (i tried multiple different locations) this error appears: "Could not save the package: [Errno 2] No such file or directory: 'c:\\users\USERNAME\\appdata\local\temp\\adv_9xp4q\\content.xml'"
Windows 7 - Version 1.0

**Comment by oaubert** [comment]
Does the c:\users\USERNAME\appdata\local\temp\adv_9xp4q exist? And, bonus question, does the USERNAME contain accented characters?

**Comment by AdaTsche** [comment]
After crash & reboot the "adv_9xp4q"-folder didn't exist (anymore?). Instead there is now "adv_9h3og0" with an content.xml. Bonus answer: Username has just plain text.

**Comment by oaubert** [comment]
There was an issue with the handling of some characters (especially \u2018 and \u2019). It is fixed in the development version by the advene/74d82accd5f404bcab9d358d1383f2732d3a0367 commit.
