### ISSUE TITLE
Problem installing on Ubuntu 20

### ISSUE THREAD

**Issue by lisboarocha** [oaubert/advene#60]
Hello,

When installing on Ubuntu 20, i get this:
> The following packages have unmet dependencies:
>  advene : Depends: gir1.2-webkit-3.0 but it is not installable
> E: Unable to correct problems, you have held broken packages

Could you help me?

Best regards,
Waldir

**Comment by oaubert** [comment]
Hi. Thanks for the report. Ubuntu20 removed an older component (the webkit HTML widget), that I had to update. I have just fixed it in the code, I will do a .deb package release including this fix next week, that should make the package installable on Ubuntu20.

**Comment by lisboarocha** [comment]
Merci beaucoup!

**Comment by oaubert** [comment]
It is now solved with the release of Advene 3.9.
