### ISSUE TITLE
the video is all striped 

### ISSUE THREAD

**Issue by sportegioco** [oaubert/advene#61]
I try to import an MP4 video but the video is all striped 
thank you very much for this wonderful job

This is my log:
administrator@natale14:~/Scaricati/advene-master/bin$ python3 ./advene
You seem to use a development tree at:
/home/administrator/Scaricati/advene-master.
WARNING:root:Using specified path /home/administrator/Scaricati/advene-master
root WARNING Advene v. 3.9 release 20210127 run at 28/01/21 11:05:15 CET on linux
advene.gui.main INFO Using localedir /home/administrator/Scaricati/advene-master/locale
advene.util.audio INFO Using gstreamer to play sounds
advene.core.mediacontrol WARNING mediacontrol: using gstreamer
advene.player.gstreamer WARNING using gtksink
advene.core.controller INFO Registering Log messages
advene.core.controller INFO Registering Trace Timeline view
advene.core.controller INFO Registering HTML content handler
advene.core.controller INFO Registering Shot validation view plugin
advene.core.controller INFO Registering Default GUI actions
advene.gui.main INFO Cannot register TracePreview: the goocanvas python module does not seem to be available.
advene.core.controller INFO Registering Trace preview
advene.core.controller INFO Registering Trace view
advene.core.controller INFO Registering Default content handlers
advene.core.controller INFO Registering Kinect view/control plugin
advene.core.controller INFO Registering Package importer view plugin
advene.core.controller INFO Registering Videoplayer view plugin
advene.core.controller INFO Registering Interactive query plugin
advene.core.controller INFO Registering Timeline view plugin
advene.core.controller INFO Registering Relation display plugin
advene.core.controller INFO Registering EditionHistory view plugin
advene.core.controller INFO Registering Bookmarks view plugin
advene.core.controller INFO Registering Link view plugin
advene.core.controller INFO Registering ActiveBookmarks view plugin
advene.core.controller INFO Registering Edit accumulator view plugin
advene.core.controller INFO Registering Annotation display plugin
advene.core.controller INFO Registering Package finder view plugin
advene.core.controller INFO Registering Transcription view plugin
advene.core.controller INFO Registering Tagbag view plugin
advene.core.controller INFO Registering Element tabular view plugin
advene.core.controller INFO Registering TALES browser view plugin
advene.core.controller INFO Registering Montage view plugin
advene.core.controller INFO Registering AnnotationImporter view plugin
advene.core.controller INFO Registering Note-taking view plugin
advene.core.controller INFO Registering GStreamer video recorder
advene.core.controller INFO Registering Dummy video player
advene.core.controller INFO Registering GStreamer video player
advene.core.controller INFO Registering Sound enveloppe importer
advene.core.controller INFO Registering Scenechange detection filter
advene.core.controller INFO Registering Youtube XML importer
advene.core.controller INFO Registering AdA RDF exporter
advene.core.controller INFO Registering VIAN importer
advene.core.controller INFO Registering Anvil importer
advene_app_plugins_brltty WARNING BrlTTY connection error: couldn't connect to b':0' with key b'keyfile:/etc/brlapi.key+polkit': b'connect: File o directory non esistente'
(brlerrno 11, libcerrno 2, gaierrno 0)
Is BRLTTY really running?
advene.core.controller INFO Registering BrlTTY actions
advene.core.controller INFO Registering Video montage renderer
advene.core.controller INFO Registering Motioncell detection filter
advene.core.controller INFO Registering DCP importer
advene.core.controller INFO Registering TurTLe (RDF) importer
advene.core.controller INFO Registering WebAnnotation importer
advene.core.controller INFO Registering AdA rdflib exporter
advene.core.controller INFO Registering Dominant color importer
advene.core.controller INFO Registering AdA OWL importer
advene.core.controller INFO Registering HPI plugin
advene_app_plugins_tts INFO TTS: Automatically using Generic TTSEngine.
advene.core.controller INFO Registering Text-To-Speech actions
advene.core.controller INFO Registering ShotDetectApp importer
advene.core.controller INFO Registering Keyword extraction plugin
advene.core.controller INFO Registering TED transcription importer
advene.core.controller INFO Registering Cinelab importer
advene.core.controller INFO Registering MPEG7 importer
advene_app_plugins_pocketsphinx WARNING Cannot register speech recognition: Pocketsphinx plugins not found. See http://cmusphinx.sourceforge.net/wiki/gstreamer for details.
advene.core.controller INFO Registering Speech recognition
advene.core.controller INFO Registering Base importer collection
advene.core.controller INFO Registering Transcriber importer
advene.core.controller INFO Registering Final Cut Pro XML importer
advene.core.controller INFO Registering Shot detection importer
advene.core.controller INFO Registering Feature detection importer
advene.core.controller INFO Registering Undo Manager
advene.core.controller INFO Registering ELAN importer
advene.core.controller INFO Registering Audio segmentation importer
advene.core.controller INFO Registering AnnotationGraph importer
advene.core.controller INFO Registering AEIDON importer
advene.core.controller INFO Registering ShotDetect XML importer
advene.core.controller INFO Registering WebAnnotation JSON-LD exporter
advene.gui.main INFO Package new_pkg loaded: No annotation and No relation.
advene.gui.main INFO Loaded package Template package
advene.player.gstreamer WARNING check player
advene.gui.main INFO Activating package Template package
advene.player.gstreamer WARNING Problem when seeking into media

![advene](https://user-images.githubusercontent.com/18140655/106121855-4f46fa00-6158-11eb-8d7d-9b95058fc15e.png)

**Comment by oaubert** [comment]
Does your video play fine in standard video players? It looks like an encoding issue. Advene uses gstreamer to play videos, so you can try to run `gst-launch-1.0 playbin uri=file:///path/to/the/video.mp4` to  see if it plays correctly (it should display the same thing as Advene). Can you also post the output of `gst-discoverer-1.0 /path/to/video.mp4` to get the encoding information.

**Comment by sportegioco** [comment]
thanks for the quick response 
As you can see the video works perfectly with the command you suggested:
gst-launch-1.0 playbin uri=file:///media/administrator/D/0Archivi/filmatoDiProva.mp4

And this is the output of the command you suggested: 
gst-discoverer-1.0 /media/administrator/D/0Archivi/filmatoDiProva.mp4
Analyzing file:///media/administrator/D/0Archivi/filmatoDiProva.mp4
Done discovering file:///media/administrator/D/0Archivi/filmatoDiProva.mp4

Topology:
  container: Quicktime
    audio: MPEG-4 AAC
    video: H.264 (Main Profile)

Properties:
  Duration: 0:01:00.256000000
  Seekable: yes
  Live: no
  Tags: 
      codec audio: MPEG-4 AAC audio
      bitrate massimo: 125588
      bitrate: 125588
      encoder: Lavf58.29.100
      formato contenitore: ISO MP4/M4A
      codec video: H.264 / AVC

But in the advene window he continues to see himself in stripes and these are the messages that the log returns to me in the terminal:
advene.core.controller INFO Registering WebAnnotation JSON-LD exporter
advene.gui.main INFO Package new_pkg loaded: No annotation and No relation.
advene.gui.main INFO Loaded package Template package
advene.player.gstreamer WARNING check player
advene.gui.main INFO Activating package Template package
advene.player.gstreamer WARNING Problem when seeking into media


![advene2](https://user-images.githubusercontent.com/18140655/106142376-b4f3b000-6171-11eb-876a-d768fa66ffd4.png)

**Comment by sportegioco** [comment]
I have tried with many mp4 movies and the result is always the same .... if you want I can try with other formats

**Comment by oaubert** [comment]
It may be one of the overlay filters that Advene uses on top of the video. Could you try running the following pipeline:
`gst-launch-1.0 uridecodebin uri=file:///path/to/video.mp4 ! videoconvert ! textoverlay halignment=center valignment=top text="test" ! rsvgoverlay data='<svg width="640" height="480"><rect x="50" y="50" width="50" height="50" fill="#00f"></rect></svg>' ! videoconvert ! autovideosink` ? It should display the video with a "test" label at the top-center, and a blue square in the top-left corner.

**Comment by sportegioco** [comment]
Yes, I try now.

In the meantime I send you these tests:
.mov format  it works very well 
.avi   format  it works very well 
.m4v format it doesn't work, all striped like mp4 
.wmv format format it doesn't work, all striped like mp4

**Comment by sportegioco** [comment]
Yes, this command it works exactly as you said
administrator@natale14:~$ gst-launch-1.0 uridecodebin uri=file:///media/administrator/D/0Archivi/filmatoDiProva.mp4 ! videoconvert ! textoverlay halignment=center valignment=top text="test" ! rsvgoverlay data='<svg width="640" height="480"><rect x="50" y="50" width="50" height="50" fill="#00f"></rect></svg>' ! videoconvert ! autovideosink

![advene3](https://user-images.githubusercontent.com/18140655/106145494-e8d0d480-6175-11eb-8c43-8b92a46bb071.png)

**Comment by oaubert** [comment]
Do you  have a sample non-working mp4 somewhere that I could test against?

**Comment by sportegioco** [comment]
I send you my machine information
Ubuntu LTS Focal Fossa
...and the file is a simple file i downloaded from youtube and I attach 
The audio works perfectly even inside advene 

https://user-images.githubusercontent.com/18140655/106148102-ef148000-6178-11eb-89f4-deaaeca7cf54.mp4



 administrator@natale14:~$ uname -a
Linux natale14 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by oaubert** [comment]
Works perfecly for me in Advene. It could be a number of things: X11 vs Wayland (on ubuntu). You could also try to modify the video output device for the video player: according to the logs, you are using gtk which is the default. You can try the other options through Edit/Preferences/Player-related (and restarting advene after each switch, to make sure it is not a dynamic video output switch issue).

**Comment by sportegioco** [comment]
I use x11 because it doesn't start with wyland advene, it gives the following error: 
(advene:78914): Gtk-WARNING **: 15:29:53.571: GtkSocket: only works under X11
(advene:78914): Gdk-WARNING **: 15:29:53.581: ../../../../../gdk/x11/gdkwindow-x11.c:5633 drawable is not a native X11 window

I also tried all available video outputs, through Edit/Preferences/Player-related, and restarting advene after each switch ... but the result is always the same

**Comment by sportegioco** [comment]
... I found the solution for almost all formats, except mp4 and m4v ... which continue to be played with video all in lines.

The format of youtube, webm and the avi format instead that do not work well, because they were going too fast now they work well.

The solution is to change line 158 of the gstreamer.py file to be like this:
sink = 'gtksink sync = false'
to so:
sink = 'gtksink'

If you tell me how to print in the terminal of the final command of gstreamer I can try to debug also the mp4 and m4v files ... which by the way are the most used.

I tried on windows and it works fine but on linux ubuntu LTS focal fossa doesn't work.

**Comment by sportegioco** [comment]
This is the output in terminal when load mp4 video:
advene.player.gstreamer WARNING check player
advene.player.gstreamer WARNING Problem when seeking into media

**Comment by oaubert** [comment]
Thanks for your investigations.  The ubuntu issue is strange, it may be related to Wayland. Did you try to open a X session instead?
For the sync=false it is a recent addition to try to workaround issues on windows, which is a failure. I removed it.

To get a representation of the pipeline, it is built through the python API so you cannot get a standard gstreamer pipeline representation. However, you can get access to the pipeline using methods from the plugin: launch and pause the video, then start the python evaluator (View/Evaluator, or Ctrl-e) and enter the command 
`c.player.str_element(c.player.video_sink)`
It will dump the video sink definition.
You also have the possibility to enable debug messages for gstreamer using the ADVENE_DEBUG environment variable: `ADVENE_DEBUG=advene.player.gstreamer ./bin/advene`

On my computer (Debian), playing a mp4 file gives as video output pipeline
```
/GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/ (bin)
    .sink[video/x-raw]ghosts GstVideoConvert:videoconvert1.GstPad:sink<= ../GstPlaySinkVideoConvert:vconv.GstGhostPad:src
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstVideoConvert:videoconvert1 (videoconvert)
            .sink[video/x-raw]<= ../GstBin:bin1.GstGhostPad:sink.GstProxyPad:proxypad1
            .src[video/x-raw]=> GstVideoScale:videoscale1.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstVideoScale:videoscale1 (videoscale)
            .sink[video/x-raw]<= GstVideoConvert:videoconvert1.GstPad:src
            .src[video/x-raw]=> GstQueue:queue1.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstQueue:queue1 (queue)
            .sink[video/x-raw]<= GstVideoScale:videoscale1.GstPad:src
            .src[video/x-raw]=> GstRsvgOverlay:overlay.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstRsvgOverlay:overlay (rsvgoverlay)
            .sink[video/x-raw]<= GstQueue:queue1.GstPad:src
            .src[video/x-raw]=> GstTextOverlay:captioner.GstPad:video_sink
            .data_sink<= None
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstTextOverlay:captioner (textoverlay)
            .video_sink[video/x-raw]<= GstRsvgOverlay:overlay.GstPad:src
            .text_sink<= None
            .src[video/x-raw]=> GstVideoConvert:videoconvert2.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstVideoConvert:videoconvert2 (videoconvert)
            .sink[video/x-raw]<= GstTextOverlay:captioner.GstPad:src
            .src[video/x-raw]=> GstGtkSink:sink.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstGtkSink:sink (gtksink)
            .sink[video/x-raw]<= GstVideoConvert:videoconvert2.GstPad:src
```

**Comment by sportegioco** [comment]
In reply at "Thanks for your investigations. The ubuntu issue is strange, it may be related to Wayland. Did you try to open a X session instead?"
...is not possible that is related to Wayland because at moment i use X session, not Wayland. I use tigervnc and other tool that don't run well on Wayland. But i have done many try olso with wayland and don't start advene. Only if i do this command:
GDK_BACKEND=x11 python3 ./bin/advene


This is the output in Evaluetor for the mp4 video, of command:
c.player.str_element(c.player.video_sink)

/GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/ (bin)
    .sink[video/x-raw]ghosts GstVideoConvert:videoconvert1.GstPad:sink<= ../GstPlaySinkVideoConvert:vconv.GstGhostPad:src
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstVideoConvert:videoconvert1 (videoconvert)
            .sink[video/x-raw]<= ../GstBin:bin1.GstGhostPad:sink.GstProxyPad:proxypad1
            .src[video/x-raw]=> GstVideoScale:videoscale1.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstVideoScale:videoscale1 (videoscale)
            .sink[video/x-raw]<= GstVideoConvert:videoconvert1.GstPad:src
            .src[video/x-raw]=> GstQueue:queue1.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstQueue:queue1 (queue)
            .sink[video/x-raw]<= GstVideoScale:videoscale1.GstPad:src
            .src[video/x-raw]=> GstRsvgOverlay:overlay.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstRsvgOverlay:overlay (rsvgoverlay)
            .sink[video/x-raw]<= GstQueue:queue1.GstPad:src
            .src[video/x-raw]=> GstTextOverlay:captioner.GstPad:video_sink
            .data_sink<= None
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstTextOverlay:captioner (textoverlay)
            .video_sink[video/x-raw]<= GstRsvgOverlay:overlay.GstPad:src
            .text_sink<= None
            .src[video/x-raw]=> GstVideoConvert:videoconvert2.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstVideoConvert:videoconvert2 (videoconvert)
            .sink[video/x-raw]<= GstTextOverlay:captioner.GstPad:src
            .src[video/x-raw]=> GstGtkSink:sink.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin1/GstGtkSink:sink (gtksink)
            .sink[video/x-raw]<= GstVideoConvert:videoconvert2.GstPad:src


advene.gui.main INFO Activating package Template package
advene.player.gstreamer DEBUG update_status start None 
advene.player.gstreamer WARNING Problem when seeking into media
advene.player.gstreamer DEBUG update_status pause None 
advene.player.gstreamer DEBUG -------------------------------- snapshot taken 0 <bound method Player.snapshot_taken of <advene.player.gstreamer.Player object at 0x7f46eb390df0>>
advene.player.gstreamer DEBUG -------------------------------- snapshot taken 23980 <bound method Player.snapshot_taken of <advene.player.gstreamer.Player object at 0x7f46eb390df0>>
advene.player.gstreamer DEBUG -------------------------------- snapshot taken 25980 <bound method Player.snapshot_taken of <advene.player.gstreamer.Player object at 0x7f46eb390df0>>
advene.player.gstreamer DEBUG -------------------------------- snapshot taken 27980 <bound method Player.snapshot_taken of <advene.player.gstreamer.Player object at 0x7f46eb390df0>>
advene.player.gstreamer DEBUG -------------------------------- snapshot taken 29980 <bound method Player.snapshot_taken of <advene.player.gstreamer.Player object at 0x7f46eb390df0>>
advene.player.gstreamer DEBUG update_status resume None 
advene.player.gstreamer DEBUG update_status pause None 
advene.player.gstreamer DEBUG -------------------------------- snapshot taken 4028 <bound method Player.snapshot_taken of <advene.player.gstreamer.Player object at 0x7f46eb390df0>>


You have developed this beautiful "advene" project and I would like to be able to make it work better on ubuntu.
I also tried and used the other project you work on, frametrail which works directly from the browser and that also surprised me for the many features.

I'm a gym teacher and I use video annotations to demonstrate my athletes' strengths and weaknesses. I have also seen "longomatch", "kinovea" and other projects, ... and maybe you could recommend me some other projects as you are a super expert, but advene is very simple and efficient.

Keep helping me and tell me what kind of rehearsals I should do. If you want I am also available to connect with you via team viewer to work directly on my computer

**Comment by sportegioco** [comment]
I recently upgraded to ubuntu 20.10 and I inform you that advene now works perfectly even with mp4 files
I was not able to identify what the problem on ubuntu 20.04 LTS, but now it works and that's what matters.
Thank you

**Comment by oaubert** [comment]
Great. Thanks for the report. I will keep an eye on the issue, but will probably focus on other issues.

**Comment by marcgregory01** [comment]
I think i might have the same problem with Linux Mint 21.04. @oaubert did you figure out anything about this? Here is my log file :

WARNING 2021-04-26 17:54:07,018 root Advene v. 3.12 release 20210416 run at 26/04/21 17:54:07 CEST on linux
INFO 2021-04-26 17:54:07,161 advene.gui.main Using localedir /usr/share/locale
INFO 2021-04-26 17:54:07,278 advene.util.audio Using gstreamer to play sounds
WARNING 2021-04-26 17:54:07,530 advene.core.mediacontrol mediacontrol: using gstreamer
WARNING 2021-04-26 17:54:07,646 advene.player.gstreamer using gtksink
INFO 2021-04-26 17:54:07,735 advene.core.controller Registering Videoplayer view plugin
INFO 2021-04-26 17:54:07,736 advene.core.controller Registering HTML content handler
INFO 2021-04-26 17:54:07,736 advene.core.controller Registering Log messages
INFO 2021-04-26 17:54:07,736 advene.core.controller Registering Trace view
INFO 2021-04-26 17:54:07,737 advene.core.controller Registering Default content handlers
INFO 2021-04-26 17:54:07,737 advene.core.controller Registering Package importer view plugin
INFO 2021-04-26 17:54:07,742 advene.core.controller Registering Default GUI actions
INFO 2021-04-26 17:54:07,743 advene.gui.main Cannot register TracePreview: the goocanvas python module does not seem to be available.
INFO 2021-04-26 17:54:07,743 advene.core.controller Registering Trace preview
INFO 2021-04-26 17:54:07,743 advene.core.controller Registering Shot validation view plugin
INFO 2021-04-26 17:54:07,743 advene.core.controller Registering Kinect view/control plugin
INFO 2021-04-26 17:54:07,774 advene.core.controller Registering Edit accumulator view plugin
INFO 2021-04-26 17:54:07,774 advene.core.controller Registering Transcription view plugin
INFO 2021-04-26 17:54:07,774 advene.core.controller Registering Tagbag view plugin
INFO 2021-04-26 17:54:07,775 advene.core.controller Registering ActiveBookmarks view plugin
INFO 2021-04-26 17:54:07,775 advene.core.controller Registering Element tabular view plugin
INFO 2021-04-26 17:54:07,775 advene.core.controller Registering Link view plugin
INFO 2021-04-26 17:54:07,775 advene.core.controller Registering TALES browser view plugin
INFO 2021-04-26 17:54:07,775 advene.core.controller Registering Timeline view plugin
INFO 2021-04-26 17:54:07,775 advene.core.controller Registering Package finder view plugin
INFO 2021-04-26 17:54:07,775 advene.core.controller Registering Annotation display plugin
INFO 2021-04-26 17:54:07,776 advene.core.controller Registering Relation display plugin
INFO 2021-04-26 17:54:07,776 advene.core.controller Registering EditionHistory view plugin
INFO 2021-04-26 17:54:07,776 advene.core.controller Registering Interactive query plugin
INFO 2021-04-26 17:54:07,776 advene.core.controller Registering Bookmarks view plugin
INFO 2021-04-26 17:54:07,787 advene.core.controller Registering AnnotationExporter view plugin
INFO 2021-04-26 17:54:07,788 advene.core.controller Registering Note-taking view plugin
INFO 2021-04-26 17:54:07,788 advene.core.controller Registering Montage view plugin
INFO 2021-04-26 17:54:07,788 advene.core.controller Registering AnnotationImporter view plugin
INFO 2021-04-26 17:54:07,834 advene.core.controller Registering GStreamer video player
INFO 2021-04-26 17:54:07,835 advene.core.controller Registering Dummy video player
INFO 2021-04-26 17:54:07,835 advene.core.controller Registering GStreamer video recorder
INFO 2021-04-26 17:54:08,072 advene.core.controller Registering TurTLe (RDF) importer
INFO 2021-04-26 17:54:08,073 advene.core.controller Registering MPEG7 importer
INFO 2021-04-26 17:54:08,073 advene.core.controller Registering VIAN importer
INFO 2021-04-26 17:54:08,073 advene.core.controller Registering Audio segmentation importer
INFO 2021-04-26 17:54:08,073 advene.core.controller Registering Scenechange detection filter
INFO 2021-04-26 17:54:08,074 advene.core.controller Registering HPI plugin
INFO 2021-04-26 17:54:08,074 advene.core.controller Registering AEIDON importer
WARNING 2021-04-26 17:54:08,074 advene_app_plugins_keywords nltk module is not available. Keyword extract plugin is disabled.
INFO 2021-04-26 17:54:08,074 advene.core.controller Registering Keyword extraction plugin
INFO 2021-04-26 17:54:08,074 advene.core.controller Registering Feature detection importer
INFO 2021-04-26 17:54:08,074 advene.core.controller Registering Motioncell detection filter
INFO 2021-04-26 17:54:08,075 advene.core.controller Registering Transcriber importer
INFO 2021-04-26 17:54:08,075 advene.core.controller Registering WebAnnotation importer
INFO 2021-04-26 17:54:08,075 advene.core.controller Registering Dominant color importer
WARNING 2021-04-26 17:54:08,075 advene_app_plugins_brltty BrlTTY connection error: couldn't connect to b':0' with key b'keyfile:/etc/brlapi.key+polkit': b'connect: Aucun fichier ou dossier de ce type'
(brlerrno 11, libcerrno 2, gaierrno 0)
Is BRLTTY really running?
INFO 2021-04-26 17:54:08,076 advene.core.controller Registering BrlTTY actions
INFO 2021-04-26 17:54:08,076 advene.core.controller Registering Cinelab importer
INFO 2021-04-26 17:54:08,076 advene.core.controller Registering Anvil importer
INFO 2021-04-26 17:54:08,076 advene.core.controller Registering AnnotationGraph importer
INFO 2021-04-26 17:54:08,076 advene.core.controller Registering Final Cut Pro XML importer
INFO 2021-04-26 17:54:08,077 advene.core.controller Registering Undo Manager
INFO 2021-04-26 17:54:08,077 advene.core.controller Registering Youtube XML importer
INFO 2021-04-26 17:54:08,077 advene.core.controller Registering ELAN importer
INFO 2021-04-26 17:54:08,077 advene.core.controller Registering ShotDetectApp importer
INFO 2021-04-26 17:54:08,077 advene.core.controller Registering TED transcription importer
WARNING 2021-04-26 17:54:08,078 advene_app_plugins_pocketsphinx Cannot register speech recognition: Pocketsphinx plugins not found. See http://cmusphinx.sourceforge.net/wiki/gstreamer for details.
INFO 2021-04-26 17:54:08,078 advene.core.controller Registering Speech recognition
INFO 2021-04-26 17:54:08,078 advene.core.controller Registering ShotDetect XML importer
INFO 2021-04-26 17:54:08,078 advene.core.controller Registering DCP importer
WARNING 2021-04-26 17:54:08,078 advene_app_plugins_ada_rdflib_export rdflib module is not available. AdARDFExporter plugin is disabled.
INFO 2021-04-26 17:54:08,078 advene.core.controller Registering AdA rdflib exporter
INFO 2021-04-26 17:54:08,079 advene.core.controller Registering AdA OWL importer
INFO 2021-04-26 17:54:08,079 advene.core.controller Registering AdA RDF exporter
INFO 2021-04-26 17:54:08,079 advene.core.controller Registering Video montage renderer
INFO 2021-04-26 17:54:08,079 advene.core.controller Registering Shot detection importer
INFO 2021-04-26 17:54:08,079 advene.core.controller Registering Sound enveloppe importer
INFO 2021-04-26 17:54:08,079 advene.core.controller Registering WebAnnotation JSON-LD exporter
INFO 2021-04-26 17:54:08,080 advene_app_plugins_tts TTS: Automatically using Generic TTSEngine.
INFO 2021-04-26 17:54:08,080 advene.core.controller Registering Text-To-Speech actions
INFO 2021-04-26 17:54:08,080 advene.core.controller Registering Base importer collection
INFO 2021-04-26 17:54:08,097 advene.gui.main Package new_pkg loaded: No annotation and No relation.
INFO 2021-04-26 17:54:08,099 advene.gui.main Loaded package Template package
WARNING 2021-04-26 17:54:08,099 advene.player.gstreamer check player
INFO 2021-04-26 17:54:08,100 cherrypy.error [26/Apr/2021:17:54:08] ENGINE Bus STARTING
INFO 2021-04-26 17:54:08,100 cherrypy.error [26/Apr/2021:17:54:08] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO 2021-04-26 17:54:08,206 cherrypy.error [26/Apr/2021:17:54:08] ENGINE Serving on http://127.0.0.1:1234
INFO 2021-04-26 17:54:08,206 cherrypy.error [26/Apr/2021:17:54:08] ENGINE Bus STARTED
INFO 2021-04-26 17:54:08,385 advene.gui.main Activating package Template package
INFO 2021-04-26 17:54:08,392 cherrypy.error [26/Apr/2021:17:54:08] ENGINE Bus STARTING
INFO 2021-04-26 17:54:08,393 cherrypy.error [26/Apr/2021:17:54:08] ENGINE Monitor thread '_TimeoutMonitor' already started.
INFO 2021-04-26 17:54:08,393 cherrypy.error [26/Apr/2021:17:54:08] ENGINE Already serving on http://127.0.0.1:1234
INFO 2021-04-26 17:54:08,393 cherrypy.error [26/Apr/2021:17:54:08] ENGINE Bus STARTED

**Comment by oaubert** [comment]
I never could reproduce this issue on any setup, so I cannot investigate. Does the pipeline mention in https://github.com/oaubert/advene/issues/61#issuecomment-769051966 work for you?

**Comment by sportegioco** [comment]
Now in ubuntu 20.10 and in ubuntu 21.04 works perfectly

**Comment by marcgregory01** [comment]
I think I got the same output that @sportegioco posted earlier : 

/GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin2/ (bin)
    .sink[video/x-raw]ghosts GstVideoConvert:videoconvert3.GstPad:sink<= ../GstPlaySinkVideoConvert:vconv.GstGhostPad:src
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin2/GstVideoConvert:videoconvert3 (videoconvert)
            .sink[video/x-raw]<= ../GstBin:bin2.GstGhostPad:sink.GstProxyPad:proxypad49
            .src[video/x-raw]=> GstVideoScale:videoscale2.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin2/GstVideoScale:videoscale2 (videoscale)
            .sink[video/x-raw]<= GstVideoConvert:videoconvert3.GstPad:src
            .src[video/x-raw]=> GstQueue:queue3.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin2/GstQueue:queue3 (queue)
            .sink[video/x-raw]<= GstVideoScale:videoscale2.GstPad:src
            .src[video/x-raw]=> GstRsvgOverlay:overlay.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin2/GstRsvgOverlay:overlay (rsvgoverlay)
            .sink[video/x-raw]<= GstQueue:queue3.GstPad:src
            .src[video/x-raw]=> GstTextOverlay:captioner.GstPad:video_sink
            .data_sink<= None
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin2/GstTextOverlay:captioner (textoverlay)
            .video_sink[video/x-raw]<= GstRsvgOverlay:overlay.GstPad:src
            .text_sink<= None
            .src[video/x-raw]=> GstQueue:queue4.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin2/GstQueue:queue4 (queue)
            .sink[video/x-raw]<= GstTextOverlay:captioner.GstPad:src
            .src[video/x-raw]=> GstVideoConvert:videoconvert4.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin2/GstVideoConvert:videoconvert4 (videoconvert)
            .sink[video/x-raw]<= GstQueue:queue4.GstPad:src
            .src[video/x-raw]=> GstGtkSink:sink.GstPad:sink
        /GstPlayBin:player/GstPlaySink:playsink/GstBin:vbin/GstBin:bin2/GstGtkSink:sink (gtksink)
            .sink[video/x-raw]<= GstVideoConvert:videoconvert4.GstPad:src

I guess I'll re-download a forth-coming version of advene when linux mint upgrade.
Meanwhile, i convert mp4 to AVI and it works just fine. Anyway, thank you for this project, it really helps me a lot to synthesize and structure abstract thinking while watching podcasts :)
