### ISSUE TITLE
Export Website - Export as static html pages

### ISSUE THREAD

**Issue by sportegioco** [oaubert/advene#62]

**Comment by sportegioco** [comment]
Export annotations so you can use them on a website

There is a menu, File, Website Export, which allows you to export annotations, even if with reduced functionality, as also written in the guide.

Unfortunately it does not work, in fact the html page it exports does not have the thumbnails (I attached images) and both on windows and on linux it reports the following errors:

(advene:7794): GStreamer-WARNING **: 16:06:48.742: ../gst/gstpad.c:4368:gst_pad_chain_data_unchecked:<vaapidecode1:sink> Got data flow before segment event
advene.core.controller ERROR General exception <class 'TypeError'> '<' not supported between instances of 'str' and 'int' <traceback object at 0x7ff1800d5e40>
NoneType: None
Traceback (most recent call last):
  File "/home/administrator/Scaricati/advene-release-3.11.8/lib/advene/gui/main.py", line 4917, in do_conversion
    self.controller.website_export(destination=d,
  File "/home/administrator/Scaricati/advene-release-3.11.8/lib/advene/core/controller.py", line 2735, in website_export
    exporter.website_export()
  File "/home/administrator/Scaricati/advene-release-3.11.8/lib/advene/util/website_export.py", line 470, in website_export
    self.write_data(url, self.fix_links(content),
  File "/home/administrator/Scaricati/advene-release-3.11.8/lib/advene/util/website_export.py", line 381, in write_data
    f.write(bytes(self.controller.package.imagecache[t]))
  File "/home/administrator/Scaricati/advene-release-3.11.8/lib/advene/core/imagecache.py", line 189, in __getitem__
    if key is None or key < 0:
TypeError: '<' not supported between instances of 'str' and 'int'

*****

However, I saw on the advene.org site that there are 4 working examples, but there is no specific procedure that allows these exports.
Is it possible to have a small guide, step by step, to export directly as static html pages to be used on a personal site? 

Thank you

![01](https://user-images.githubusercontent.com/18140655/109319084-c900ff00-784e-11eb-80e6-8c41dcff9783.png)
![02](https://user-images.githubusercontent.com/18140655/109319104-cc948600-784e-11eb-85d2-816e9ccfe177.png)

**Comment by oaubert** [comment]
This feature was indeed non-functional and untested, after the python3/gtk3 port. I just did some fixes to address most of the issues, please test from a fresh git version and report any issues you may find. For the documentation, would you be interested to write something (with a user point of view, which will be more relevant) according to your experience, in the Advene wiki?

**Comment by sportegioco** [comment]
Sure, gladly. Unfortunately my English is the result of google translator, so you will have to look at the translation.
I will try to write a little guide on the wiki based on my experience

**Comment by sportegioco** [comment]
I tried advene and i am surprised of how many possibilities it offers.
But unfortunately it is not well documented and I have not been able to understand many things
If you help me understand them, I can write other guides such as export website that can help others to use advene as well 

******

In Note-Taking editor, when i set the size of snapshot, i have this error:

advene.core.controller ERROR General exception <class 'TypeError'> popup() missing 1 required positional argument: 'activate_time' <traceback object at 0x7fab4827bf40>
NoneType: None
Traceback (most recent call last):
  File "/home/administrator/advene/lib/advene/gui/edit/transcribe.py", line 1156, in scale_snaphots_menu
    m.popup(None, None, None, 0, Gtk.get_current_event_time())
TypeError: popup() missing 1 required positional argument: 'activate_time'

*******

When i go to file, process video, the system many time is blocked and i have found in advene path, some foder with bad character encoding ...I attach image 
![badcharacter](https://user-images.githubusercontent.com/18140655/109394201-10a68a00-7926-11eb-83c1-582b8cea1bcc.png)

*******

Now website export go, and in my folder there is a file index.html with User-defined static views that is ok, but file frame.html is bad, i think because there is not src for video_player, but also because when open frame.html and clik on link don't open in right frame :
<frameset cols="70%,30%">
  <frame name="main" src="index.html" />
  <frame name="video_player" src="" />
</frameset> 

Template for youtube video is better than template for local video, but has only start and end time as description, (00:00:01.222 - 00:00:06.824) and not have the text of annotation

If you tell me how to make template, i can try to write some template

![framenongo_01](https://user-images.githubusercontent.com/18140655/109394215-24ea8700-7926-11eb-8363-19b187dcbaa9.png)
![framenongo_02](https://user-images.githubusercontent.com/18140655/109394217-287e0e00-7926-11eb-876b-11f8e8740f76.png)

******

In static website export, there is a way to have a player that support some annotation like text overlay or subtitles ...or other annotation?
I think it's a good idea to insert a web player that supports certain annotations, like javascript or even php, that you can insert into your website. 

******

I have not understand how to make the Transcription, the Table of contents and export all as html page, like in:
https://www.advene.org/examples/tbl_linked_data_html5/transcript.html
Can you explain it to me? ... and then I can write a guide for that too 

******

Another chapter of advene that i have not understand are Relation. I can create a relation by drag an annotation over other annotation in timeline, but when i start web interface and i go to Package content exploration, i find simple relation ...but if i open it i found none [, , ]

What are Relation?
What can i do with relation?

******
I think it's a good idea to insert a web player that supports certain annotations, like javascript or even php, that you can insert into your website. 

*****

Its a good idea, when open a package, all active bookmark must refresh snapshot ...and when i export website in html page all thumbnail must be refresh  so that there is not blank thumbnail.
*****

Is there a way to annotate with overlaid web pages, pdf, link to web, surveys or other resources as happens with frametrail? 

*****

advene is a wonderful software with a lot of features. Congratulations on the wonderful job you are doing.
Thank you

**Comment by oaubert** [comment]
Thanks for these detailed reports. Can you send a mail (see my website olivieraubert.net for the address) so that we can arrange a direct call?
