### ISSUE TITLE
Hard Crash when using "Scene Change Detection"

### ISSUE THREAD

**Issue by AdaTsche** [oaubert/advene#66]
Advene crashes when using "Scene change detection" in vers. 3.11.13-27-g4bb1fc33 on Ubuntu 18.4 and also Ubuntu 20.
After processing the video for a while advene closes and Terminal shows "killed".

/usr/lib/python3/dist-packages/gi/overrides/GObject.py:553: Warning: ../../../../gobject/gsignal.c:2642: instance '0x278a500' has no handler with id '34049'
  return func(*args, **kwargs)
Killed

in further tests on new and blank packages the process just takes forever without leading to results but without crashing advene.
Tested with multiple videos and packages.

**Comment by oaubert** [comment]
Thanks for the report, I have added a fix for this issue.
