### ISSUE TITLE
Video extracting feature is not available

### ISSUE THREAD

**Issue by YvonnePfeilschifter** [oaubert/advene#69]
I am working with Advene development version release/3.12 on Ubuntu 18.04.4 LTS.

When trying to export a video with "Extract video" (clicking right on a selection of annotations and choosing the "Extract video" option), I get a notification that reads: "The video extracting feature is not available." 

Tested on different packages and videos and on a second computer using the same Advene and Ubuntu version.

**Comment by oaubert** [comment]
The video extraction feature depends on the Gstreamer Editing Services. It is mentioned as just a suggestion in the Advene .deb dependencies, so it is not necessarily installed. You can `apt install gir1.2-ges-1.0`, which provides the video extraction feature.
If that works for you, then could you close this issue?

**Comment by YvonnePfeilschifter** [comment]
That is working, thank you a lot!
