### ISSUE TITLE
Internal HTML Viewer - Blank page

### ISSUE THREAD

**Issue by staphon7** [oaubert/advene#73]
Hello there,  

My operating system is Arch Linux.  

Here is the output of `advene --version`:
- Advene development version release/3.12-39-g8e93ab32

How to reproduce the issue:
- Launch Advene with `./bin/advene /<path_to>/Nosfertu_v13.azp`.
- Drag the button "Open a comment view in the browser" button to the right side of the embedded video.
- Click on "Cast" - First item - and then click on "Jonathon Harker" link.

Result:
- The link works well, but the "HTML Viewer" page becomes blank.
- We have to click the "Left arrow" button in order to display the page back.

Question:
- Is that reproducible on your side?

Thank you

**Comment by oaubert** [comment]
Thanks for noticing this. I knew this issue, but it was low on my todo list as a minor detail. Now that you made it an actual issue, I had to fix it :-)
