### ISSUE TITLE
Shot validation view - Mouse wheel

### ISSUE THREAD

**Issue by staphon7** [oaubert/advene#74]
Hello there,  

My operating system is Arch Linux.  

Here is the output of `advene --version`:
- Advene development version release/3.12-39-g8e93ab32

How to reproduce the issue:
- Launch Advene with `./bin/advene /<path_to>/Nosfertu_v13.azp`.
    - Right click on an annotation type and click on "Shot validation...".  
OR
    - Right click on an single annotation and click either on "Begin: xx:xx:xx.xxx" or "End: xx:xx:xx.xxx".
- Drag the mouse over the left/right side of the view and scroll with the mouse wheel.

Actual result:
- Scrolling with the mouse wheel does not do anything.

Expected result:
- We should be going forward/back through the movie.

Question:
- Is it the same thing in your side?

Thank you

**Comment by oaubert** [comment]
Thanks for the detailed bug report (and for the others while I am at it, it is much appreciated). I have fixed this issue in the git version, the fix will be included in the next release.
