### ISSUE TITLE
Screenshot Discrepancy

### ISSUE THREAD

**Issue by AdaTsche** [oaubert/advene#8]
In the note taking editor advene uses sometimes a different screenshot for the timemarker than the main videoplayer shows. This becomes apparent when creating a timemarker at the end of a shot. The main videoplayer shows the first image of the next shot while the time-marker-screen-shot shows the last frame from the previous shot. Probably it is just a visual discrepancy and not relevant for the underlying timecode.

**Comment by oaubert** [comment]
Duplicate of #15
