### ISSUE TITLE
Avene not opening on Windows 11

### ISSUE THREAD

**Issue by Grantelbart3D** [oaubert/advene#97]
Hello,

Advene which i have used for work for a couple of months without a problem has suddenly stopped working after closing it. When I try to open it, there is no response at all. My computer has a file called "advene.log", which logged the following text at the last time I used it:

WARNING 2024-08-04 00:28:47,888 advene.rules.ecaengine Trying to remove non-existant rule Rule 'internal' from internal ruleset
WARNING 2024-08-04 00:28:47,890 advene.rules.ecaengine Trying to remove non-existant rule Rule 'internal' from internal ruleset
WARNING 2024-08-04 00:28:47,890 advene.rules.ecaengine Trying to remove non-existant rule Rule 'internal' from internal ruleset
WARNING 2024-08-04 00:28:47,891 advene.rules.ecaengine Trying to remove non-existant rule Rule 'internal' from internal ruleset
ERROR 2024-08-04 00:28:47,921 advene.rules.ecaengine ********** ATTRIBUTE ERROR for rule 0x1a9d28ab670 **********
ERROR 2024-08-04 00:28:47,921 advene.rules.ecaengine ********** ATTRIBUTE ERROR for rule 0x1a9d2544fa0 **********
ERROR 2024-08-04 00:28:47,921 advene.rules.ecaengine ********** ATTRIBUTE ERROR for rule 0x1a9d28c6070 **********

I tried everything, even uninstalling and installing it again didn't help. Please help me!

**Comment by oaubert** [comment]
The error messages from the log do not seem to be linked to the non-start of the application.
You can try to launch Advene from a text command prompt, there may be other messages. Launch a command prompt, and type advene. It should display additional textual messages on startup.

**Comment by Grantelbart3D** [comment]
thank you for your answer, but even if I try to launch it from a text command prompt, there is no reaction.

**Comment by Grantelbart3D** [comment]
ok, it suddenly started working again

**Comment by Grantelbart3D** [comment]
thank you
